- name: ec2 instance
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - ./vars_files/zk_vars.yml
    - ./vars_files/ec2_vars.yml
  tasks:
  - name: provision a set of instances
    ec2:
      key_name: my-ec2-key
      region: "{{ec2.region}}"
      group: "{{ec2.group}}"
      instance_type: t2.micro
      image: "{{ ec2.ami_id }}"
      wait: true
      exact_count: 3
      count_tag:
        Name: Zookeeper
      instance_tags:
        Name: Zookeeper
    register: ec2

  - name: Add all instance public IPs to host group
    add_host: hostname={{ item.public_ip }} groups=ec2hosts
    with_items: ec2.instances

  - name: wait for SSH to come up
    local_action: wait_for
                  host={{item.public_ip}}
                  port=22
                  state=started
    with_items: ec2.instances

  
- hosts: ec2hosts
  name: configuration play
  user: ubuntu
  gather_facts: true
  sudo: True

  vars_files:
    - ./vars_files/zk_vars.yml

  tasks:
  - name: install zookeeper dependency
    command: "{{item}}" 
    with_items:
      - sudo apt-get update -y
      - sudo apt-get -y install default-jdk

  - name: download zookeeper and unzip
    command: "{item}"
    with_items:
      - cd /home/ubuntu
      - sudo wget {{zk.source}}
      - sudo tar -zxvf zookeeper-{{zk.version}}.tar.gz
      - rm zookeeper-{{zk.version}}.tar.gz
      - sudo mkdir /opt/zookeeper
      - sudo mv zookeeper-{{zk.version}} /opt/zookeeper
      # set zoo.cfg file
      - sudo mkdir /opt/zookeeper/zkdata
      - sudo mkdir /opt/zookeeper/logs

  - name: create zookeeper configuration file
    template: src=./templates/zoo.cfg.j2 dest=/opt/zookeeper/zoo.cfg

  - name: Set Zookeeper Id
    copy: >
      content={{ item.0 + 1 }}
      dest=/opt/zookeeper/zkdata/myid
    with_indexed_items: "{{groups['ec2hosts']}}"
    when: item.1 == "{{inventory_hostname}}"
