- name: deploy zookeeper and storm on ec2 instances cluster
  hosts: localhost
  connection: local
  gather_facts: False
  roles:
  - ec2

- name: deploy zookeeper and storm on ec2 instances cluster
  hosts: ec2hosts
  user: ubuntu
  become: yes
  become_method: sudo
  gather_facts: true
  roles:
  - zookeeper
  - storm