---
- name: install zookeeper dependency
  command: "{{item}}" 
  with_items:
    - sudo apt-get update -y
    - sudo apt-get -y install default-jdk

- name: download zookeeper and unzip
  command: "{item}"
  with_items:
    - cd /home/ubuntu
    - sudo wget {{zk.source}}
    - sudo tar -zxvf zookeeper-{{zk.version}}.tar.gz
    - rm zookeeper-{{zk.version}}.tar.gz
    - sudo mkdir /opt/zookeeper
    - sudo mv zookeeper-{{zk.version}} /opt/zookeeper
    # set zoo.cfg file
    - sudo mkdir /opt/zookeeper/zkdata
    - sudo mkdir /opt/zookeeper/logs